# Site settings
title: Real Time Stock Price Tracker
email: ephnjor@gmail.com
url: https://ephnjor2021.github.io/stock-price
description: "Investors, traders, and enthusiasts can timely access accurate data to make informed decisions about buying or selling stocks."
keywords: "stock prices, real-time stock data"
skills: "Where Data Meets Opportunity"
meta_author: Ephraim Gathoni

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Ephraim Gathoni
  location: Location
  social: Reach Me At
  credits: Team Members

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/NJOROGEEPHRAIM
  - title: facebook
    url: https://web.facebook.com/ephraim.njoroge1
  - title: linkedin
    url: https://www.linkedin.com/in/ephraim-njoroge/
  - title: bitbucket
    url:
  - title: github
    url: https://github.com/ephnjor2021

# Postal address (add as many lines as necessary)
address:
  - line: 659 10100
  - line: Nairobi, KE

# Credits content
credits: 'Real Time Price Tracker was created by <a href="https://twitter.com/NJOROGEEPHRAIM">Ephraim Gathoni</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
